### ISSUE TITLE
add posix support for milliseconds timestamps

### ISSUE THREAD

**Issue by aguilajesus** [log2timeline/dfdatetime#115]
currently we have PosixTimeInMicroseconds, we should have an equivalent for milliseconds

**Comment by joachimmetz** [comment]
There is JavaTime (https://github.com/log2timeline/dfdatetime/blob/master/dfdatetime/java_time.py#L13) which technically is PosixTimeInMilliseconds. Could you provide me with the context where you're trying to apply this?

**Comment by aguilajesus** [comment]
I will used JavaTime as suggested. Thanks Joachim.

**Comment by joachimmetz** [comment]
Moved the functionality of JavaTime into PosixTimeInMilliseconds
https://github.com/log2timeline/dfdatetime/pull/119

Keeping JavaTime as an alias.
