### ISSUE TITLE
add APFS time support

### ISSUE THREAD

**Issue by pstirparo** [log2timeline/dfdatetime#116]
APFS, as represent the number of nano seconds elapsed since January 1, 1970. 
Ref: "Decoding the APFS file system"
http://cyberforensicator.com/wp-content/uploads/2017/11/DIIN_698_Revisedproof.1-min-ilovepdf-compressed.pdf

**Comment by joachimmetz** [comment]
@aguilajesus indicated to pick this up

**Comment by joachimmetz** [comment]
Updated https://github.com/log2timeline/dfdatetime/wiki/Date-and-time-values

**Comment by joachimmetz** [comment]
Assuming the APFS timetamp is a signed value for now.

**Comment by joachimmetz** [comment]
WIP by @aguilajesus https://github.com/aguilajesus/dfdatetime/tree/apfs-time
