### ISSUE TITLE
Formatting dates sometimes returns January zeroth

### ISSUE THREAD

**Issue by creideiki** [log2timeline/dfdatetime#134]
I had some weird errors processing CSV output from `psort`, and tracked them down to a couple of lines having date stamps of "01/00/1971" or "01/00/1974", which seems wrong. Outputting JSON from `psort` instead, I got the timestamps in POSIX format, and tracked the error to `dfdatetime`.

The original error occurred on an up-to-date Fedora 29, running `plaso-20181219-3` out of [LiFTeR](https://forensics.cert.org/repository/) on Python 2.7.15, but the error is still there when running the current master of `dfdatetime` (0b23e033af30e8a8d289207a70083b2a4c3e3015).

```
$ python2
>>> from dfdatetime import posix_time as dfdatetime_posix_time
>>> dfdatetime_posix_time.PosixTime(31511228).CopyToDateTimeString()
u'1971-01-00 17:07:08'
>>> dfdatetime_posix_time.PosixTime(126189827).CopyToDateTimeString()
u'1974-01-00 12:43:47'
```

The same bug is present in the `PosixTimeInMilliseconds()` and `PosixTimeInMicroseconds()` interfaces (which is what `psort` actually uses).

`date` says those timestamps were on the 31:st of December the year before, not the zeroth of January:
```
$ env LC_TIME=en_US TZ=UTC date --date='@31511228'
Thu Dec 31 17:07:08 UTC 1970
$ env LC_TIME=en_US TZ=UTC date --date='@126189827'
Mon Dec 31 12:43:47 UTC 1973
```

**Comment by joachimmetz** [comment]
Issue is that `interface._GetDateValues` does not correctly handle number of days (in year) of 0. 

Pending fixes: https://github.com/log2timeline/dfdatetime/pull/135

With fix:
```
In [2]: from dfdatetime import posix_time

In [3]: posix_time.PosixTime(31511228).CopyToDateTimeString()
Out[3]: u'1970-12-31 17:07:08'

In [4]: posix_time.PosixTime(126189827).CopyToDateTimeString()
Out[4]: u'1973-12-31 12:43:47'
```

**Comment by joachimmetz** [comment]
Changes merged and new pre-release made available.

**Comment by creideiki** [comment]
Thanks! I just tried the 20190116 release on my real data, and it solves the problem.
